### PR TITLE
Adds the air hockey example

### PR DESCRIPTION
**Pull request by Ivan-267**

### CODE REVIEW

**Comment by edbeeching** [comment]
@Ivan-267 This looks great! Did you manage to train an agent yet? It would be good to include the ONNX file in the PR if you have it?

**Comment by Ivan-267** [comment]
I've made some fixes after my video on Discord which was a trained model, so I'll have to retrain for the onnx file. After I train it, I'll add the onnx.

**Comment by Ivan-267** [comment]
Video of the trained onnx model at x2 speedup set in sync node:

https://github.com/edbeeching/godot_rl_agents_examples/assets/61947090/7029832a-611b-4907-88d2-fd16885087ae

**Review by edbeeching — APPROVED** [review]
Thanks for the model, the video looks awesome, LGTM!

**Comment by edbeeching** [comment]
Ye go for it

**Pull request merged**
