### PR TITLE
Adds Lander3D env

### PR DESCRIPTION
**Pull request by Ivan-267**
#### ONNX video
https://github.com/edbeeching/godot_rl_agents_examples/assets/61947090/221f6f5b-bbd4-4560-a6d5-473c0231f480

#### Description
A 3D Lander env where the task is to land safely and as close as possible to the goal position. This env uses the discrete actions branch, and needs it for:

- Optimal training (training should work with main branch gdrl, although the discrete actions will pass binary conversion unnecessarily, but onnx export will not work without the branch), 
- ONNX inference, the plugin from the discrete actions branch is packaged with this env and is required to run it.

I added this information to the readme so users will know the requirements for now, until the discrete actions branch is potentially merged.

Detailed description of env is present in readme: https://github.com/edbeeching/godot_rl_agents_examples/blob/3d_lander_example/examples/3DLander/readme.md

> Running inference:
> 
> To start inference using the pretrained onnx, open the testing_scene in Godot Editor, then press F6 or click on the scene starting icon

Known issues:
There is a rare error caused by an `inf` value being sent by an observation noticed during training. It hasn't been investigated or resolved.

#### Tasks
- [x] Add environment files
- [x] Upload working onnx (~16m timesteps)
- [x] Experiment with changes, retrain and upload onnx if it performs better (uploaded: ~10m timesteps)
- [x] Add description to this PR
- [x] Complete readme
- [x] Maybe add video to repo, depending on how the performance is
- [x] Final quick test of starting inference and training with `gdrl` after cloning the repository

### CODE REVIEW

**Comment by edbeeching** [comment]
hey @Ivan-267 and am just trying out this example. I have the following error:

image

**Comment by Ivan-267** [comment]
Hello,

Thanks for testing the env.

I had this issue before due to blend.import files being needed (it turns it into the correct Rigidbody class), so I added an additional .gitignore file in 3DLander/blender to include the files for this example.

I tried downloading the zip from the branch on github website and it loads for me in Godot 4.2.1 stable.

Can you check if you have the .gitignore file in blender folder in the example and specifically if you see the blend.import files (before Godot makes them upon first load)? At the moment I'm not sure what causes the issue, maybe it works different on a different PC.

**Comment by edbeeching** [comment]
Ah perhaps I need to re-add my blender path. I will try again tomorrow.

**Review by edbeeching — APPROVED** [review]
@Ivan-267 I had to double click on the lander.blend file and click reimport and then everything worked. It was probably a bug on the Godot side? Perhaps add a comment to the line that throws the error in case anyone else has the same issue? Otherwise LGTM, you may need to rebase / merge main though.

**Comment by Ivan-267** [comment]
> @Ivan-267 I had to double click on the lander.blend file and click reimport and then everything worked. It was probably a bug on the Godot side? Perhaps add a comment to the line that throws the error in case anyone else has the same issue? Otherwise LGTM, you may need to rebase / merge main though.

The comment is a great idea, I'll definitely add something. Maybe I have some cache locally or my Godot version is slightly different, for now the comment should resolve it. The merge conflict is probably about the readme (each env adds its own video), I'll check that too.

**Pull request merged**
